### ISSUE TITLE
iOS [CoreLocation] This method can cause UI unresponsiveness if invoked on the main thread. 

### ISSUE THREAD

**Issue by RedHappyLlama** [tlserver/flutter_map_location_marker#79] opened 2023-08-14 17:46 UTC
Hi,

The following code produces an error: ``[CoreLocation] This method can cause UI unresponsiveness if invoked on the main thread. Instead, consider waiting for the `-locationManagerDidChangeAuthorization:` callback and checking `authorizationStatus` first.``

              FollowOnLocationUpdate _centerOnLocationUpdate = FollowOnLocationUpdate.never;
              late StreamController<double> _centerCurrentLocationStreamController;

              @override
              void initState() {
              super.initState();
              _centerOnLocationUpdate = FollowOnLocationUpdate.always;
              _centerCurrentLocationStreamController = StreamController<double>();
               }

....

            child: FlutterMap(
              mapController: mapController,
              options: MapOptions(
                center: LatLng(centerLat, centerLng),
                zoom: _zoom,
                enableMultiFingerGestureRace: true,
                maxZoom: 18,
                minZoom: 4.0,
                onTap: (context, latLng) {
                  _popupLayerController.hideAllPopups();
                  selectedGuide = null;
                },
                onPositionChanged: (MapPosition position, bool hasGesture) {
                  _popupLayerController.hideAllPopups();
                  if (hasGesture) {
                    setState(() => _centerOnLocationUpdate = FollowOnLocationUpdate.never);
                  }
                },
              ),
              children: [
                  CurrentLocationLayer(
                    followCurrentLocationStream: _centerCurrentLocationStreamController.stream,
                    followOnLocationUpdate: _centerOnLocationUpdate,
                    style: LocationMarkerStyle(
                      marker: Container(
                        decoration: BoxDecoration(
                          color: myBlueColour,
                          borderRadius: BorderRadius.circular(30.0),
                          border: Border.all(style: BorderStyle.solid, color: Colors.white, width: 5.0),
                        ),
                      ),
                      markerSize: const Size(25.0, 25.0),
                      accuracyCircleColor: myBlueColourTransparent,
                      headingSectorColor: myBlueColour,
                    ),
                  ),

May be related to https://github.com/Baseflow/flutter-geolocator/issues/1151.

Any help would be much appreciated.

**Comment by tlserver** [comment] 2023-08-15 13:16
Can you provide more information, such as which system / platform, which version of OS & flutter & FMLM & FM?

**Comment by RedHappyLlama** [comment] 2023-08-25 13:31
> Can you provide more information, such as which system / platform, which version of OS & flutter & FMLM & FM?

Apologies for the delay! Details below:

- iOS only, both virtual and physical devices. All recent iOS.
- Flutter 3.10.4
- FMLM: 7.0.2
- FM: 5.0.0

**Comment by tlserver** [comment] 2023-09-13 04:54
Sorry, I do not have a iOS device to test it. If you found this problem is caused by this plugin but not its dependency, a PR would be help. Otherwise, you may want to create an issue in that reso and close this.

**Comment by RedHappyLlama** [comment] 2023-09-15 12:07
Hi,

I get around the issue with the code below which might help? I believe the issue might be related to using an old version of the iOS Geolocator problem. See https://github.com/Baseflow/flutter-geolocator/issues/1151. Unfortunately I'm relatively new to coding and Flutter so not sure I can be much more help right now?

                  Platform.isIOS
                      ? CurrentLocationLayer(
                          //TODO eventually remove this
                          positionStream: Geolocator.getPositionStream().asyncMap(
                            (event) => LocationMarkerPosition(
                                latitude: event.latitude,
                                longitude: event.longitude,
                                accuracy: event.accuracy),
                          ),
                          followCurrentLocationStream: _centerCurrentLocationStreamController.stream,
                          followOnLocationUpdate: _centerOnLocationUpdate,
                          style: LocationMarkerStyle(
                            marker: Container(
                              decoration: BoxDecoration(
                                color: myBlueColour,
                                borderRadius: BorderRadius.circular(30.0),
                                border: Border.all(style: BorderStyle.solid, color: Colors.white, width: 5.0),
                              ),
                            ),
                            markerSize: const Size(25.0, 25.0),
                            accuracyCircleColor: myBlueColourTransparent,
                            headingSectorColor: myBlueColour,
                          ),
                        )

**Closed** 2023-10-19 17:00 UTC
